AWSTemplateFormatVersion: "2010-09-09"
Description: "Create VPC"

# ------------------------------------------------------------#
# Parameters
# ------------------------------------------------------------#
Parameters:
  Prefix:
    Type: "String"
  Environment:
    Type: "String"
  VpcCidrBlock:
    Type: "String"

# ------------------------------------------------------------#
# Resources
# ------------------------------------------------------------#
Resources:
  # ------------------------------------------------------------#
  # VPC
  # ------------------------------------------------------------#
  Vpc:
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: "Name"
          Value: !Sub "${Prefix}-${Environment}-vpc"

# ------------------------------------------------------------#
# Outputs
# ------------------------------------------------------------#
Outputs:
  Vpc:
    Value: !Ref Vpc
    Export:
      Name: !Sub "${Prefix}-${Environment}-vpc"